### ISSUE TITLE
Use the Z.json file to install modules

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#10]

**Comment by ottiker** [comment]
This would require these steps to install a module:
1. Read the instance composition and get the module's git url.
2. Clone the module into the project.
3. Read the `Z.json` and create an module composition file.

**Comment by IonicaBizau** [comment]
I would say clone & read because we will not depend on git provider APIs.

**Comment by ottiker** [comment]
Moved issue to the [jillix/service](https://github.com/jillix/service) repo. [issue number 14](https://github.com/jillix/service/issues/14)
