### ISSUE TITLE
Require inside of custom modules (joint)

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#102]
Can we require client files in custom modules (joint module)?

I don't guess so, but what are the alternatives?

**Comment by ottiker** [comment]
Good idea! But the `joint` module is responsible to pass `engine` functionality to the custom code, such as `require`, `module` and `exports`. Thus this issue can be moved to the [adioo/joint](https://github.com/adioo) repo.

**Comment by ottiker** [comment]
Issue moved to https://github.com/adioo/joint/pull/2
