### ISSUE TITLE
Is there a use case when models should load views or other IVM elements? 

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#108]
In other words, should we allow user to add IVM elements to models?

**Comment by ottiker** [comment]
Yes I think so, cause we don't know yet all use cases. And since every IVM can load other IVMs, it's already working.

**Comment by IonicaBizau** [comment]
This complicates the logic. Views are namespaced with instance names. So, if instance `iA` loads view `vB` that loads model `mC` and our customer adds view `vD` on `mC`, then it should be saved as `/composition/views/iA_vD.json`.

**Comment by IonicaBizau** [comment]
Same scenario we have when a view loads another view.

**Comment by ottiker** [comment]
True. Then only `views` and `instances` should be able to load `views`. And models can only load other `models` or `instances`.

**Comment by ottiker** [comment]
And of course `views` and `instances` can also load `instances` and `models`.
