### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#110]
How do we handle file uploads in Engine?

**Comment by ottiker** [comment]
With `links`. The only difference are the `arguments` in the handler function.
1. Define the link (the event is in the url: `/@/[instance]/[event]`)
2. Define a method like here: [engine/lib/module/module.js#L436-L452](https://github.com/jillix/engine/blob/master/lib/module/module.js#L436-L452)

**Comment by ottiker** [comment]
The `req` and `res` streams, which are required for an upload, are in the `this.link` object.

**Comment by IonicaBizau** [comment]
Thanks!

**Comment by IonicaBizau** [comment]
@adioo I get _Instance or operation not found._...

**Comment by IonicaBizau** [comment]
It seems that the error appears only when I access it in another tab (as url). Why?
