### ISSUE TITLE
Calling `route` with a relative path doesn't trigger route to O config

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#111]
``` js
{
  ...,
  "O": {
    "events": [{"re": "^/foo", "A": {...}}]
  },
  ...
```

If I do `Z.route("bar")` the url becomes `/foo/bar`, but the act handler from the observer config above will not be triggered.

**Comment by ottiker** [comment]
Routes have to be absolute (relative routes are not yet implemented). The reason why `^/foo` is not reacting, is because the `route` event itself is still `bar`, but the the browser updates the `url` relative, cause it has no `/` in the beginning. So the `url` is different then the `route` event.

**Comment by ottiker** [comment]
Dynamic routing can be done, by using `*` wildcards in the url.
Current url: `/dynamic-foo/`
Emit route: `/*/bar` => `/dynamic-foo/bar`
Listen to dynamic url: `^/[^/]+/bar`
