### ISSUE TITLE
Open link in a new Tab

### ISSUE THREAD

**Issue by ottiker** [jillix/flow-nodejs#14]
Disable default prevention of DOM click events when `ctrl/cmd` is pressed.
Also look at the middle mouse click behavior.

**Comment by gabipetrovay** [comment]
Check out this [SO answer](http://stackoverflow.com/a/24715737/454103) to my question.

**Comment by ottiker** [comment]
I guess in most cases it's sufficient to just render a HTML link, with the desired `url`.

Example:

``` html
<a if="myElement" href="http://{myLink.href}" target="_blank">{myLink.name}</a>
```

Additionally, if there's an 'DOM event' appended by the `composition`, then it's possible to disable the "preventing" of default actions from the browser.

Example:

``` json
{
    "selector": "#myElement",
    "dontPrevent": true,
    "in": "mouseenter",
    "out": [{}]
}
```

And the case, that an new tab must be opened from a configuration, should be handled in the module layer (Module code). 

Example:

``` json
{
    "selector": "#mySpecialElement",
    "in": "click",
    "out": [{
        "call": "openNewWindow",
        "to": "windowOpener",
        "data": {
            "url": "http://my.url.com/whatever",
            "target": "_blank"
        }
    }]
}
```
