### ISSUE TITLE
Implement HTTP2

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#146]
Probably one of the important things when using the service in the real world, we have to enable https:

https://github.com/jillix/engine/blob/c8899067e149a7f3c3949c8a9686ec7c3bb7a5d8/lib/engine.js#L4

**Comment by ottiker** [comment]
The plan is to use `http 2` or `spdy`, which only work with encryption.

**Comment by IonicaBizau** [comment]
:+1:
