### ISSUE TITLE
Generate dummy fingerprints for non-committed files

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#147]
I remember @adioo fixed this, but it's now broken again...

**Comment by ottiker** [comment]
@IonicaBizau in which branch?

**Comment by IonicaBizau** [comment]
I'm on `v0.1.0-beta`, but it can be fixed in any branch. It's not so critical, but it's important.

**Comment by ottiker** [comment]
ok, I'll fix it in the `npm-engine-modules` branch.

**Comment by IonicaBizau** [comment]
:+1:
