### ISSUE TITLE
Engine Framework Logo proposal

### ISSUE THREAD

**Issue by lcristianiim** [jillix/flow-nodejs#154]
Hello team!  
If we have a brand new framework to develop beautiful apps it would be appropriate that we should also have a logo for it.  
I have created a vector logo as a logo proposal. Please check it out.  
![engine](https://cloud.githubusercontent.com/assets/9945624/6502818/a62497d8-c32f-11e4-8025-92925e577dc3.jpg)

**Comment by IonicaBizau** [comment]
Wowowow! Nice! :+1:

**Comment by ottiker** [comment]
Yeah! now we need a sleek CSS Animation, which makes the engine rattle and run :smile:
