### ISSUE TITLE
Is the config field still used?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#156]
https://docs.google.com/a/jillix.com/drawings/d/1JL4PaJjawA0h593ea5oOEs8WlC8HSs1GZnZrvXF0GWw/edit

**Comment by ottiker** [comment]
You mean the `config` and the `client.config` fields? They are still in use, this is the place where we can store module specific configurations. See [here](https://github.com/jillix/service/blob/master/composition/private.json#L8-L76)

**Comment by IonicaBizau** [comment]
What about `config`? Is that server side config?

**Comment by ottiker** [comment]
Yes

**Comment by IonicaBizau** [comment]
Thanks! :+1:
