### ISSUE TITLE
Merge set data into emit

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#159]

**Comment by IonicaBizau** [comment]
https://github.com/jillix/engine/blob/6566f656ae0e30fd238ba0f0f868d3d8204bb577/lib/client/flow.js#L76

We have to merge the data from the original instance not from the `to` one:

``` js
data = handleDataMerging(config, event, data, _module_instance);
//                                            ^
```

**Comment by ottiker** [comment]
Agree, the original `module_instance` should be used to search the values. :+1:

**Comment by IonicaBizau** [comment]
Closing since it's fixed in beta.
