### ISSUE TITLE
The websocket connection is randomly closed sometimes

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#160]
I'm not sure what's going on but sometimes the ws connection is killed and the site goes unresponsive.

**Comment by ottiker** [comment]
Well, every time you restart the `engine` process, the websocket connection is closed. Then you have to reload the page. Or did you encounter, that a websocket connection is closed without stopping the process?

**Comment by IonicaBizau** [comment]
I'm not talking about a process restart but sometimes the ws is closed... Just like that. No _visible_ reasons.

**Comment by ottiker** [comment]
Does others also experience this issue? If yes, please provide the `node` or `iojs` version number.
@gabipetrovay 
@lcristianiim

**Comment by lcristianiim** [comment]
I have not encountered this issue.
My node version: v0.12.0
