### ISSUE TITLE
How to we handle global key events?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#161]
For example, if I want to listen for <kbd>CTRL</kbd> + <kbd>S</kbd> only on `/foo` but not on the `/bar` route how can I do that since the page is not reloaded?

**Comment by ottiker** [comment]
Maybe you should consider to use a "focused" state, to enable the keyboard input. Cause only when the editor (or an module which uses keyboard commands) is focused, it should react on the keyboard-commands.

And another solution could be, to listen to the `url` events and enable/disable the keyboard-commands.

``` json
[{
    "in": "^/foo/?$",
    "out": [
        {
            "call": "enableKeyboardCommands"
        }
    ]
},
{
    "in": "^/(?!foo)/?$",
    "out": [
        {
            "call": "disableKeyboardCommands"
        }
    ]
}]
```

@IonicaBizau What is your use case?

**Comment by IonicaBizau** [comment]
:+1: 

I'm not yet convinced, but closing this for now.
