### ISSUE TITLE
Link sends data over closed websocket

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#164]
``` sh
$ engine /home/ionicabizau/Documents/_engineApps//service/ 10001
/home/ionicabizau/Documents/_engineApps/engine/node_modules/ws/lib/WebSocket.js:214
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/home/ionicabizau/Documents/_engineApps/engine/node_modules/ws/lib/WebSocket.js:214:16)
    at Object.send (/home/ionicabizau/Documents/_engineApps/engine/lib/client/link.js:218:17)
    at Object.Link.end (/home/ionicabizau/Documents/_engineApps/engine/lib/client/link.js:50:14)
    at /home/ionicabizau/Documents/_engineApps/engine/lib/module.js:144:18
    at /home/ionicabizau/Documents/_engineApps/engine/lib/comp.js:134:21
    at Object.exports.prepareComponents (/home/ionicabizau/Documents/_engineApps/engine/lib/file.js:217:16)
    at /home/ionicabizau/Documents/_engineApps/engine/lib/comp.js:83:25
    at /home/ionicabizau/Documents/_engineApps/engine/lib/comp.js:307:20
    at /home/ionicabizau/Documents/_engineApps/engine/lib/comp.js:263:9
    at handler (/home/ionicabizau/Documents/_engineApps/engine/lib/file.js:263:13)
```

**Comment by ottiker** [comment]
When does this error happen?

**Comment by IonicaBizau** [comment]
Randomly... But it's annoying.

**Comment by ottiker** [comment]
Maybe this issue has somethings to do with issue #160. Probably the problems lies in the `link` logic. I think this error appears, cause enigne tries to send data over a already closed websocket.

**Comment by IonicaBizau** [comment]
Maybe yes or maybe no. For example that happend in the first request: I started the process and opened the page in the browser. Then the process crashed.

**Comment by ottiker** [comment]
In the error message we can see that the `link.end` is called, before `link.send`.

``` sh
Object.send (_engineApps/engine/lib/client/link.js:218:17)
Object.Link.end (_engineApps/engine/lib/client/link.js:50:14)
```

...and then the websocket modules says, that the socket is `not opened`.

**Comment by lcristianiim** [comment]
I've just started service app with engine.
Went in browser and the service app was not being displayed.
In the terminal found this: 

<pre>cristian@cristian-N76VM:~/jillix/apps/service$ engine ~/jillix/apps/service/ 10001
/home/cristian/jillix/engine/node_modules/ws/lib/WebSocket.js:214
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/home/cristian/jillix/engine/node_modules/ws/lib/WebSocket.js:214:16)
    at Object.send (/home/cristian/jillix/engine/lib/client/link.js:218:17)
    at Object.Link.end (/home/cristian/jillix/engine/lib/client/link.js:50:14)
    at /home/cristian/jillix/engine/lib/module.js:144:18
    at /home/cristian/jillix/engine/lib/comp.js:132:21
    at Object.exports.prepareComponents (/home/cristian/jillix/engine/lib/file.js:215:16)
    at /home/cristian/jillix/engine/lib/comp.js:81:25
    at /home/cristian/jillix/engine/lib/comp.js:304:20
    at /home/cristian/jillix/engine/lib/comp.js:260:9
    at handler (/home/cristian/jillix/engine/lib/file.js:261:13)
cristian@cristian-N76VM:~/jillix/apps/service$ engine ~/jillix/apps/service/ 10001
lib/file.js#83 Error: ENOENT, open '/home/cristian/jillix/apps/service/public/builder/worker-json.js''</pre>

After restarting service app with engine every thing was ok.

**Comment by IonicaBizau** [comment]
Same here.

**Comment by IonicaBizau** [comment]
This still happens even after the latest updates...

**Comment by ottiker** [comment]
@IonicaBizau Can you post the error?

**Comment by IonicaBizau** [comment]
The same one...

**Comment by ottiker** [comment]
With the same line numbers? cause the code changed in the mean time..

**Comment by IonicaBizau** [comment]
I will keep the eye on it and update this issue.

**Comment by ottiker** [comment]
:+1:
