### ISSUE TITLE
Buffer callbacks everywhere a request loads a cachable object

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#17]

**Comment by ottiker** [comment]
So far I see callback buffering in following scenarios:
- loading an `instance`
- loading a `view`
- loading a `model`
- loading a `store`
- loading a `file`

**Comment by IonicaBizau** [comment]
What about calling `req` function of a model?

**Comment by IonicaBizau** [comment]
https://github.com/jillix/node-cb-buffer

**Comment by IonicaBizau** [comment]
I think this needs an update since have only instances and `req` function is gone I guess.
