### ISSUE TITLE
Allow empty strings in `set` config

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#170]

**Comment by ottiker** [comment]
@IonicaBizau  Can you post an example `flow` config to demonstrate an empty string `set` config?

**Comment by IonicaBizau** [comment]
``` js
{
 "set": {
   "foo": "bar"
  }
}
```

If `data.bar` is `""`, `0`, `false` or any value that could be converted into `false`, the `foo` value will be `undefined`.

**Comment by ottiker** [comment]
Ok, got it. Thanks :+1:

**Comment by ottiker** [comment]
Fixed in 196cc156afb253c380f91df772488711e430be56, but not yet tested.

**Comment by IonicaBizau** [comment]
Yes! It's fixed! :sparkles:
