### ISSUE TITLE
Server websocket messages doesn't respond, after process restart

### ISSUE THREAD

**Issue by ottiker** [jillix/flow-nodejs#174]
When an engine process is restarted, the cached data in the memory is gone. Which causes the problem, when a client sends a websocket message, the server won't find the module instance, cause of the process restart. This will be solved, when we implement shared memory or other external caches.

**Comment by ottiker** [comment]
To better understand the problem, do following steps:
1. got to `/builder/service`
2. duplicate the tab
3. restart the engine process
4. reload the duplicated tab
..now the first tab is working normal again

**Comment by ottiker** [comment]
I referred this issue in the [README.md](https://github.com/jillix/engine#please-note).

**Comment by IonicaBizau** [comment]
This workaround doesn't work anymore for me. After the process restarts, the spinners appear.

**Comment by ottiker** [comment]
Which modules were loaded? Please provide more detail, otherwise it's impossible to reproduce and fix an issue.

**Comment by IonicaBizau** [comment]
1. Open the builder page.
2. Close the process.
3. Start the process again

The gears will appear.

**Comment by ottiker** [comment]
Actually you should be see the login page, cause the session is destroyed.
