### ISSUE TITLE
Don't fingerprint resources in debug mode

### ISSUE THREAD

**Issue by gabipetrovay** [jillix/flow-nodejs#180]
When debugging client code, I have to set breakpoints every time I change a file a new fingerprint is generated and DevTools loses all the breakpoint information. The breakpoints can also contain watch expressions.

It would be nice to be able to deactivate fingerprinting for debugging purposes.

**Comment by IonicaBizau** [comment]
Couldn't reproduce. The fingerprints are changed only after committing the changes.
So, just don't commit your files until the debugging is done.

**Comment by ottiker** [comment]
The fingerprints are generated with the content of a file. [see here](https://github.com/jillix/engine/blob/master/lib/file.js#L130).
Cause in a installed `npm` module, we don't have the `git` history.

**Comment by IonicaBizau** [comment]
Yes, good point! :+1: 

However, they are not changed if the process is not restarted. So, just don't kill the process.

**Comment by ottiker** [comment]
Until there's a "standard" for fingerprinting files, so that the browser can detect when a fingerprint changes, we can not do anything from the engine. Or we disable fingerprinting, but that would be a too big disadvantage.

**Comment by IonicaBizau** [comment]
It would be really handy to have an option to disable the fingerprints in dev mode. Generally I keep the dev tools opened with disabled cache.

Otherwise, we should introduce the _terrible debugging_ term. :smile: Really, it's the most annoying thing when debugging client side code.

**Comment by IonicaBizau** [comment]
@adioo Could you please push a fix for this? The client-side debugging is very difficult... :cry:

**Comment by ottiker** [comment]
This issue will be solved, when we create install scripts, which handle the compression and minification of the resources. In `debug` mode, engine will just compress the files, but they are not minified and fingerprinted.
