### ISSUE TITLE
Move the string into an object using set config

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#181]
If data is a string (e.g. `"bar"`), how can I move it as a value into an object?

``` js
"set": {
  "foo": "?????"
}
```

The result should be:

``` js
{
   "foo": "bar"
}
```

**Comment by ottiker** [comment]
Just set a `data` object:

``` json
{
    "data": {
        "foo": "bar"
    }
}
```

The data in the `data` object overwrites the data, that comes from the emit ([engine composition](https://github.com/jillix/engine#composition)).

**Comment by IonicaBizau** [comment]
The `"bar"` value is dynamic.

**Comment by ottiker** [comment]
The solution is to emit an `event` object as second parameter:

``` js
this.emit("eventName", { /*event object*/ }, { /*data object*/ })
```

@IonicaBizau Please close the issue if it works for you.

**Comment by IonicaBizau** [comment]
Yes, I moved it in the jxservice-api module. Thanks!
