### ISSUE TITLE
Handle file extensions

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#184]
`http://github.jillix.service.private.jillix.ch:10001/editor/service/package.json` :arrow_right:  `File "/editor/service/package.json" not found.`

**Comment by ottiker** [comment]
Does the file exist in the `public` folder of the application repo? Cause paths, that begin with `/` are looked up in the public folder. Or what is the use case?

**Comment by IonicaBizau** [comment]
No, it doesn't. I'm using this in the service app (when editing files).

**Comment by ottiker** [comment]
Ok, so the URL is actually not a file path, but tells the editor which file to load. We have two options, both of them have their pros and cons.
1. No `404 Not found` for file paths (always returns the engine index html document)
2. No file extensions in non file paths (`localhost:9000/editor/service/package/json`)

Which one do you think is better?

**Comment by ottiker** [comment]
Here are the public files handled: https://github.com/jillix/engine/blob/master/lib/static.js#L28-L43

**Comment by IonicaBizau** [comment]
> No file extensions in non file paths
> That would be ugly.

I :+1: for the first one. What are the cons?

**Comment by ottiker** [comment]
The drawback would be, that you wont see `404` in the network tab of the inspector. If the file is not found, engine would just return the index document.

**Comment by IonicaBizau** [comment]
That already happens for routes without an extension...

**Comment by ottiker** [comment]
True and the most files are anyway loaded from modules, which is an operation, that returns a `404` if the file is not found.

**Comment by IonicaBizau** [comment]
But we will still have a problem here: what happens if the path which is supposed to be handled by editor exists in the service app?

**Comment by ottiker** [comment]
Yes, the only solution to that problem, would be to namespace public file request. Like we have the `@` for operations. Or we use an operation URL for getting public files.
