### ISSUE TITLE
Add ^ and $ to events internally

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#185]
What are the pros/cons?

It's kind of boring to do it manually. E.g. `^save$`

Or maybe an option which will will add them by default?

**Comment by ottiker** [comment]
I think it's maybe better to do that optimization in the Builder, when we create regExp. Ex. in a detail view of a bubble. But for sure an automatization will be needed.

**Comment by ottiker** [comment]
Maybe we can move this issue to the service builder milestine..?

**Comment by IonicaBizau** [comment]
I still believe this should be fixed in engine and when we have complicated regular expressions, just pass an option to disable it.

Handing this in the builder would cause to generate same repetitive data.

**Comment by ottiker** [comment]
ups.. wrong button :blush:

**Comment by ottiker** [comment]
The service module instance detail form and builder take care of adding repetitive regexp patterns. This will not solve that repetitive data is in the composition configuration, but this trade off is worth for the flexibility we gain through regexp event names.
