### ISSUE TITLE
Change the name of the framework

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#187]

**Comment by ottiker** [comment]
Any suggestions?? I like "engine", cause it "drives" all applications.

**Comment by lcristianiim** [comment]
When naming such a big tool there are a few points which must be considered simillary to the creation of a logo :
- the tool will be commercial or it will be free?
- the targeted utilizators are companies or individual programers, or both? 
- with this tool we want to advertise jillix and attract new clients or we want to adevertise a new way of buiding apps (which one is prioritary)?
- do we have in mind to advertise it (create banners and other things)?

Only with a clear understanding of the goals we seek it can be arrived at the best "appeareance and presentation" of the framework.

Personally I think "engine" its not a bad name. Definitely anything can be improved if it needs to. 

"engine" would look nice on banners and advertising text like: "Get your engine"; "Do you have an engine?"; "Engine for your apps"; "Try the new engine"; "Let the engine work while you create apps"; "Get the engine for your apps"; "jillix developed engine for companies that need lorem ipsum..." 

How would the programers speak about the framework:
"I'm using engine"; "Have you heard of engine?"; "I like making apps with engine"

Like a logo a name must say something about the product.
For ex "engine" is saying some subliminal keywords:
- power
- mechanics
- speed
- lubrification
- noise
- etc..
  If we are satisfied with the keywords transmited by the name of the product not much must to be changed. If not, suggestions are needed.

**Comment by rolfmattes** [comment]
Thank you Johnny for opening this issue. Yes, the time is here to set up namings for the jillix environment.

We will use "jillix" as brand for the whole service/framework. ...You see where the journey goes. :-)

Inside jillix we will have a lot of other services/tools etc. From this reason it's important for users to have a clear signage/branding to identify and understand them. The same is guilty for jillix members for better understanding on what they are working on. 

jillix follows a strict brand strategy called umbrella branding.

_Umbrella brand: jillix_

Sub brands can be:  (We have to define it)
- jxService
- jxEngine
- jxBuilder
- jxAppBuilder
- jxCloud
- jxStage
- jxTraining
- etc etc

....could be also more fancy

.....ideas are warm welcome :-)

**Comment by ottiker** [comment]
Then this issue/discussion should be moved to another place, when it's not only about the engine framework.

**Comment by lcristianiim** [comment]
good point

**Comment by IonicaBizau** [comment]
@rolfmattes :+1:
