### ISSUE TITLE
How do we handle link access over roles?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#195]
How can we create a link which can be run by role `foo`, but not by role `bar`?

**Comment by ottiker** [comment]
Links just emit events on the server side flow config of an instance. That means that a instance defines the access of which events can be emitted on the server.

**Comment by IonicaBizau** [comment]
>  That means that a instance defines the access of which events can be emitted on the server.

Well, then that should be a feature. We have to avoid as much as possible checks which can be handled in engine.

In this case, we could provide the roles which have access to emit things from the client to the server and avoid other checks.

**Comment by ottiker** [comment]
When issue #2 is solved, links can be configured per role.
