### ISSUE TITLE
Using setTimeout in a server side operation never calls back

### ISSUE THREAD

**Issue by gabipetrovay** [jillix/flow-nodejs#198]
Enclosing [this](https://github.com/adioo/login/blob/master/server/login.js#L30-L45) operation into a `setTimeout` (delay `10` or `5000`, it does not matter) the [callback](https://github.com/adioo/login/blob/4cbfcc70e7daf7e744575e5c422894a76581c552/login.js#L38-L46) on the client is never called back.

**Comment by IonicaBizau** [comment]
What's the use case?

**Comment by gabipetrovay** [comment]
Killing engine! :stuck_out_tongue_winking_eye: 

There can be any code inside one operation code that delays the processing of the incoming data. And if this code is slow enough, there is a problem.

**Comment by gabipetrovay** [comment]
The problem seems with [`link.data` callback](https://github.com/adioo/login/blob/4cbfcc70e7daf7e744575e5c422894a76581c552/server/login.js#L30) that is never called back. Data events lost?

**Comment by ottiker** [comment]
I think [here](https://github.com/adioo/login/blob/master/server/login.js#L33) should be an `return`.

**Comment by IonicaBizau** [comment]
This is the expected behavior. If you send data from the client after appending the data listener, you will get the data on the server. It's like any other stream interface (e.g. the http request).

@adioo The missing `return` is not related to this issue.
