### ISSUE TITLE
Install store and model adapters on project install

### ISSUE THREAD

**Issue by ottiker** [jillix/flow-nodejs#20]
Install adapters like modules. This means we should have an adapter composition, similar with the module instance composition.

**Comment by ottiker** [comment]
Also `npm install` the database driver.

**Comment by ottiker** [comment]
Find out a configuration for a `model` to define the possible queries that can be made on a particularly `model`. Something similar, in principal, to the `links` configuration of an `instance`.

**Comment by ottiker** [comment]
After merging pull request #133, the data stores and adapters are normal modules. and not part of the engine core anymore.

**Comment by IonicaBizau** [comment]
:sparkles: :star2:

**Comment by ottiker** [comment]
@IonicaBizau When you're back we will have a lot to talk about :smile:

**Comment by IonicaBizau** [comment]
Sure, until then I support you with emoji things! :smile:

**Comment by ottiker** [comment]
:smile:
