### ISSUE TITLE
Handling @import in css

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#201]
How can we solve the css `@import`?
Since Engine doesn't know the css path, then the imported css files will not be loaded.

**Comment by ottiker** [comment]
I think this should work, since URLs are relative. Can you post the CSS where the `@import` is and the `HTTP` request headers of the imported CSS file?

**Comment by ottiker** [comment]
CSS `@import` works, but public URLs must be prefixed with `/!`. I've documented this in the engine readme file. [jillix/engine#path-types](https://github.com/jillix/engine#path-types)

**Comment by IonicaBizau** [comment]
Isn't this related to the fingerprints as well?
/cc @lcristianiim

**Comment by lcristianiim** [comment]
Tried with `/!` in the `@import` path inside a css file and it's working.

**Comment by ottiker** [comment]
Fingerprints in a request URL are optional. The static file server simply removes a fingerprint (if it exists), before reading the file.
