### ISSUE TITLE
Extend the documentation with broadcasted and targeted events

### ISSUE THREAD

**Issue by gabipetrovay** [jillix/flow-nodejs#215]
Please extend the [documentation](https://github.com/jillix/engine#emit-events) with how to:
- emit events to all other modules
- emit events to another module

**Comment by IonicaBizau** [comment]
With the new version of `blah` we could define blah templates in this very project and let blah to generate such docs for us. In case we need custom stuff in README.md that's also possible! :smile: 

https://github.com/IonicaBizau/node-blah/pull/19
