### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by gabipetrovay** [jillix/flow-nodejs#216]
Static file server does not properly serves static HTML files:

Trying to access `/!/file.html` you get the error:

`Failed to load resource: net::ERR_CONTENT_DECODING_FAILED`

**Comment by ottiker** [comment]
This cloud be a bug with/in the HTML minifier.
https://github.com/jillix/engine/blob/master/lib/file.js#L121

**Comment by IonicaBizau** [comment]
Probably helpful: http://stackoverflow.com/a/14040312/1420197

**Comment by ottiker** [comment]
:+1: That's it. Cause in engine the HTML snippets are loaded over websockets.

**Comment by IonicaBizau** [comment]
@adioo Nope, @gabipetrovay is meaning this appears when you access the HTML path using `/!/file.html`.

**Comment by ottiker** [comment]
Engine writes the `Content-Encoding` HTTP header always, which is the bug. And and cause websockets don't support binary data, like gzip, engine makes a special excuse and don't compress the HTML data.
See [here](https://github.com/jillix/engine/blob/master/lib/file.js#L194) and [here](https://github.com/jillix/engine/blob/master/lib/file.js#L119-L120).

**Comment by ottiker** [comment]
@gabipetrovay Please test pull #217, and merge if it works. Thanks!
