### ISSUE TITLE
Use npm api to install packages

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#22]
- `reuiqre('npm')`

or
- Child progress: `npm install --production`

---

`npm install` installs `devDependencies` as well.

**Comment by ottiker** [comment]
do you mean install packages for applications/projects? or can you describe a the issue a little more detailed?
cause in the engine repo currently we do the npm install manual.

**Comment by IonicaBizau** [comment]
In both engine and admin we do `exec('npm install')`, but that installs dev dependencies. I think it should be better to use `npm` api.

Also, it would be easier to add `--production` argument to `npm install` command.

**Comment by ottiker** [comment]
Good point. But this issue is an admin issue. In engine there's no `exec(npm install)`. Or where did you found an `exec(npm install)` in the engine code?

**Comment by IonicaBizau** [comment]
Exactly, `exec` commands are in admin application.

Also, there are `npm install` commands in docker files.

https://github.com/jillix/engine/search?utf8=%E2%9C%93&q=npm+install

**Comment by ottiker** [comment]
The docker containers are just copied code, they will change. I moved the issue to [admin#5](https://github.com/jillix/admin/issues/5)
