### ISSUE TITLE
Require files from other modules

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#222]
Is it possible to have an a function on the server side (maybe on client as well?) to require files from other modules?

Something like:

``` js
var mod = engine.module.requireFile("relative/path/from/the/module.js");
```

**Comment by ottiker** [comment]
Yes this is possible like this:

``` js
// client
var module = require('module@version/file.js');

// server
var module = require('module/file.js');
```

**Comment by IonicaBizau** [comment]
Actually, that will look something like this (on server):

``` js
var module = require('../node_modules/module/some/file.js');
```

But that looks ugly.

**Comment by ottiker** [comment]
On the server, since the module you require is installed with `npm`, you don't have to write the module paht. This should work:

``` js
var module = require('otherModuleName/file.js')
```
