### ISSUE TITLE
Add an option to disable wrapping for some files

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#223]
Especially for web workers, this makes sense. Or is this already implemented?

**Comment by IonicaBizau** [comment]
Maybe removing the `w=1` could disable the wrapping:

```
# Load in the window thread (by Engine)
/@/@/test-workers@0.1.0/worky.@80c82d9.js?w=1

# Load in the Worker thread, via importScripts
/@/@/test-workers@0.1.0/worky.js
```

**Comment by ottiker** [comment]
For scripts that are not in a package client dependency, avoiding the `w=1` will disable the wrapping. So just don't put the `importScripts` in the client `module` dependency list. That is anyway better, cause the `importScripts` are not used with `require`.

**Comment by IonicaBizau** [comment]
So, do I have to put them in the public directory of the module?

**Comment by ottiker** [comment]
Yes, but I guess the public directory is not working.
