### ISSUE TITLE
Load scripts as workers

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#224]
For example, I want to access the `/@/@/builder@0.2.0-beta2/client/worker-parser.@568952f.js` file, but not load it when the module is initialized but _after_, since that's a web worker.

I'm not sure what's the best way to do that.

**Comment by IonicaBizau** [comment]
Maybe a solution would be to get the absolute path dependencies in `self`. That would help somehow.

**Comment by IonicaBizau** [comment]
...because `new Worker(uri)` expects the `uri` to be absolute.

**Comment by ottiker** [comment]
Would it be a good solution, to tell a dependency script, that it should be loaded as a worker?
Package JSON:

``` json
{
    "client": {
        "module": [
            "normal/script.js"
            "(W)wokers/script.js"
        ]
    }
}
```

Module script:

``` js
var worker = require('./workers/script');
// ..use the worker instance in the module
```

Where `(W)` in a script dependency indicates, to load the script in a worker. This could also be used to create shared workers with `(S)`.

**Comment by IonicaBizau** [comment]
> Would it be a good solution, to tell a dependency script, that it should be loaded as a worker?

Nope, because I want to use _Worky_ to create new workers.

**Comment by ottiker** [comment]
And can't you pass a worker instance to Worky? or what does Worky other then `var worker = new Worker("worker.js");` ?

**Comment by ottiker** [comment]
Cause if engine's resource loader could create workers along CommonJS modules, then the scripts could be loaded in parallel.

**Comment by IonicaBizau** [comment]
> or what does Worky other then var worker = new Worker("worker.js"); ? 

It creates an `EventEmitter` like interface between threads. Maybe we can implement that directly in Engine. That would be awesome.

**Comment by ottiker** [comment]
Yes I think that's possible. I think if engine could run multithreaded applications, that would be indeed awesome :smiley:. We can discuss this tomorrow in a call.

**Comment by IonicaBizau** [comment]
@adioo Cool! Anyway, _Worky_ can live as independent js library. :smile:
