### ISSUE TITLE
Why is the client.module required?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#225]
https://github.com/jillix/engine/blob/c86aadf78fe63d461c600f53b4ebe6afd4800528/lib/static.js#L179-L181

**Comment by ottiker** [comment]
This is where the client module script paths are. Without scripts a module makes not much sense.

``` js
client.module = ["main.js", "resource.js", "..."]
```

**Comment by IonicaBizau** [comment]
@adioo But this appears for a composition file like [this](https://github.com/jillix/starter/blob/6733e7fa4a13226fbf1003acd03a4abc0a5bd052/composition/root.json#L2). I'm not sure what's going on.

**Comment by ottiker** [comment]
This is because the client module files are merged into the composition from the `package.json`.
Package:

``` json
{
    "components": {
        "client": {
            "module": ["main.js", "...js"]
        }
    }
}
```

**Comment by IonicaBizau** [comment]
@adioo Thanks! After switching to event streams branch in the view module the error is gone. :+1:

**Comment by ottiker** [comment]
:+1:
