### ISSUE TITLE
Replace the `to` flow option with a convention in the string value

### ISSUE THREAD

**Issue by gabipetrovay** [jillix/flow-nodejs#229]
The `to` flow configuration option can be replaced with a convention in the string value of other options: `call`, `emit`, `data`

``` js
{
  "on": "click",
  "selector": ".navbar-brand",
  "call": "api:project.branch.list",
  "emit": "api:branchList",
  "data": [
    "api:transform", { "set": { "project": "_path.1" } }
  ]
}
```

In the above example, the `project.branch.list` function will be called from the instance `api`, the `branchList` event will be emitted to the `api` instance and the data handler `transform` will be used from the `api` instance to handle the streamed data.

**Comment by IonicaBizau** [comment]
It can be replaced, but it's not reliable. I :-1: this because of two reasons:
- duplicated things (the instance name appears both in call and in emit values)
- the _smart_ builder should parse & stringify such values -- which makes the things more difficult

Sure, that's what I think.
