### ISSUE TITLE
waitFor in the Engine?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#23]
What's the `waitFor` configuration in Engine?

---

I have the following scenario:
- instance `A` emits a `call` to instance `B`
- `B` should be loaded, otherwise an error will be thrown

How can `A` listen for `B` load?

**Comment by ottiker** [comment]
`waitFor` should not be needed in engine. If an instance has a `L` (load) configuration, all the elements in `L` are loaded before the parent instance is initialized.
Note that if you have an `L` config in a listener/observer `O` config then the parent instance `A` is already initialized and can listen to events, which can be emitted by an other instance `B`.
