### ISSUE TITLE
Undefined urls appear in the wrapping lines

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#232]
![image](https://cloud.githubusercontent.com/assets/2864371/8519806/0b5a70be-23de-11e5-97d2-6c5cd6b48c00.png)

**Comment by ottiker** [comment]
Is there a version in the module package of `ruut`?

**Comment by IonicaBizau** [comment]
@adioo I added `"engine-ruut": "jillix/engine-ruut"` in `package.json` (app) and nothing changed...

**Comment by ottiker** [comment]
@IonicaBizau but is there a `version` property in the [jilli/engine-ruut](https://github.com/jillix/engine-ruut) `package.json` ? Cause I only see an empty repo.

Engine should throw an error, if a module don't specify a version.

**Comment by IonicaBizau** [comment]
@adioo Yeah, that was the problem! Thanks.
