### ISSUE TITLE
Load instance on event

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#234]
Is it possible to just load an instance when an event stream comes without redirecting it via `to`?

**Comment by ottiker** [comment]
you mean in a flow configuration? Otherwise the method `engine.load(instanceName, role, callback)` loads an instance. `role` can be `null` on the client.

**Comment by IonicaBizau** [comment]
> you mean in a flow configuration? 

Yes!

**Comment by IonicaBizau** [comment]
Here is a use-case:
- instance A some module renders some HTML (e.g. view)
- instance B needs in the `init` function the rendered HTML by A

Possible solution:
- on DOM rendered, **load** B

Just load it and nothing more! :boom:

**Comment by ottiker** [comment]
This should be just handled by the `load` config. If instance B needs html from instance A, instance A should load instance B with the `load` config, which ensures, that instance A is initialized before B. Also the dependencies of instance B. To imagine how the hierarchy of the loaded modules in the graph looks like, helps to understand which module must be initialized first.

**Comment by ottiker** [comment]
I'll close this issue, when dependencies of a dependency are initialized correctly.

**Comment by IonicaBizau** [comment]
> This should be just handled by the load config. 

Nope. Imagine that instance A does something async (e.g. a request to database and then it magically modifies the HTML).

**Comment by IonicaBizau** [comment]
:tada:

**Comment by ottiker** [comment]
:smile:
