### ISSUE TITLE
Event delegation

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#24]
Event delegation in `O` config?

**Comment by ottiker** [comment]
What you mean by event delegation?
Listening to an event that emits an other event on an different instance?

**Comment by IonicaBizau** [comment]
``` js
"actions": [
  {
    "selector": ".myClass",
    "name": "click",
    "A": {...}
  }
]
```

How to handle clicks for elements that were added dinamically?

**Comment by ottiker** [comment]
This should be done manually. Since you add the element dynamically (with javascript), you also can append the event handlers. But it's possible that the actions are added on an event. That means you can create the DOM dynamically, then emit an event, which has a `actions` observer config for the newly created elements.

**Comment by ottiker** [comment]
If event delegation is, what I asked in the second comment, than it is possible.

``` json
{
    "events": [{
        "re": "eventRegExp",
        "A": {
            "emit": "eventName",
            "to": "instanceName"
        }
    }]
}
```

@IonicaBizau pleas close this issue if you agree with this solution.

**Comment by IonicaBizau** [comment]
Even this:

``` js
{
    "events": [
        {
            "re": "somethingRendered",
            "A": {
                "O": {
                    "actions": [
                        {
                            "selector": ".myClass",
                            "name": "click",
                            "A": {...}
                        }
                    ]
                }
            }
        }
    ]
}
```

In Bind library we have [`delegated` property that being `true`, will catch events on dynamically added elements](https://github.com/jillix/bind#v014).

**Comment by ottiker** [comment]
The `actions` event will be added if the event is emitted after a DOM element is added, so yes this should work.
