### ISSUE TITLE
Default config in modules

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#242]
Is it possible to have a default configuration set in the `package.json` file? I see there is a `composition.config` object. Is it used? I guess it could be merged with the config (if it is not already merged). :bulb:

**Comment by ottiker** [comment]
The package's `composition.config` (server side) is merged into the composition instance [here](https://github.com/jillix/engine/blob/master/lib/composition.js#L222-L229) and the `composition.client.config` (client side) is merged [here](https://github.com/jillix/engine/blob/master/lib/composition.js#L192-L199). So, defining default configs is already possible.
