### ISSUE TITLE
404 after changing a client file in a module

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#249]
> GET http://public.service.jillix.ch:10001/@/@/engine-ruut@1.0.0/client/index.@ef3b40f.js?w=1  404

Sometimes it appears, sometimes it doesn't.

**Comment by ottiker** [comment]
@IonicaBizau let me know if this still happens with the new flow implementation.

**Comment by IonicaBizau** [comment]
I hope now -- closing for now. :+1:

**Comment by ottiker** [comment]
:+1:
