### ISSUE TITLE
`to` instance is initialized before writing data into the stream

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#250]
``` js
flow: [
  { "on": "some-event", "call": "something", "to": "some-instance" }
]
```

`some-instance` is loaded before writing data to `some-event`, before even creating `some-event` stream.

Looks like `some-instance` is loaded when parsing the flow array. If this is expected, then that's terrible... Really hope this is a bug. :smiley_cat:

**Comment by ottiker** [comment]
The `some-event` [stream is created](https://github.com/jillix/engine/blob/master/lib/client/flow.js#L37) before the `some-instance` [is loaded](https://github.com/jillix/engine/blob/master/lib/client/flow.js#L135). And the writes on the `some-event` stream [are buffered](https://github.com/jillix/engine/blob/master/lib/client/flow.js#L132-L133) until the `some-instance` is loaded and initialized. After the flow specific stream is [setup and piped](https://github.com/jillix/engine/blob/master/lib/client/flow.js#L142) to the `some-event` stream, the `some-event` stream [resume writing again](https://github.com/jillix/engine/blob/master/lib/client/flow.js#L145).
As soon the `this.flow("event")` is emitted the flow handlers, which listen with a `on` flow config, are called. They call the `call` handler and setup the `data` handler, distribute and pipe the stream objects, so when writes happen on the `var stream = this.flow('myStream')` everything is loaded and setup. There are now two layers of events, the first is the event, which distributes the stream object. And the second is the stream writes, which call the data handlers.

**Comment by IonicaBizau** [comment]
What if I _don't_ write anything to `some-event` stream? I expect that `some-instance` will not be loaded.

So, is this a bug?

**Comment by ottiker** [comment]
As soon you emit the flow event `this.flow("event")` and one of the `on` flow configs has a `"to": "instance"`, that is not loaded, flow attempts to load the "instance".

I think it should be this way, cause on "click", for example, the target instance, which changes a css class or does some form validation, should be already loaded. On the other hand engine does not call `this.flow()`, a module is responsible to decide, when to call `this.flow`.

Do you have an example, where it is suitable to wait with loading the instance?

**Comment by IonicaBizau** [comment]
> Do you have an example, where it is suitable to wait with loading the instance?

I think it's natural to wait until data comes in the stream and then to load the instance. There are cases when we init streams in the init function (`this.fooStream = this.flow("foo")`).

But I understand the issue... Maybe a solution would be to call `end()` each time when I create the stream.
