### ISSUE TITLE
Uncaught TypeError: moduleCache[cleanPath].push is not a function

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#254]
Sometimes `Uncaught TypeError: moduleCache[cleanPath].push is not a function` appears

**Comment by ottiker** [comment]
@IonicaBizau please use [this branch](https://github.com/jillix/engine/tree/file-load-debug) and report the client console output here. Thanks!

**Comment by IonicaBizau** [comment]
I guess it happens only after starting the process. Here is the log:

![image](https://cloud.githubusercontent.com/assets/2864371/8675247/71cb0926-2a4b-11e5-986e-bb5c332d032f.png)
