### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#258]
![image](https://cloud.githubusercontent.com/assets/2864371/8800287/289aa94a-2fba-11e5-98d0-e7455df1ac20.png)

**Comment by ottiker** [comment]
A simple `if` will fix the problem. This happens if a flow stream handler has not arguments configured.
Missing arguments:

``` json
{
    "flow": [
        ["load"]
    ]
}
```

With arguments:

``` json
{
    "flow": [
        ["load", ["instance1", "instanceN"]]
    ]
}
```

**Comment by IonicaBizau** [comment]
I speculate the problem is because I have a flow like this:

``` js
[
  "some-event"
  "some-instance/load"
]
```

Maybe that's the reason?

**Comment by IonicaBizau** [comment]
...that's strange, since the instances don't have the `load` method but only the `engine`.
