### ISSUE TITLE
Combine "emit" and "link" handlers

### ISSUE THREAD

**Issue by ottiker** [jillix/flow-nodejs#267]
``` txt
> to Local
==========

current                       new
---------------------------*---------------------------
["emit", "event"]          | ["flow", "event"]
["instance/emit", "event"] | ["instance/flow", "event"]
---------------------------*---------------------------

> to Server
===========

current                       new
---------------------------*----------------------------
["link", "event"]          | ["flow", "@event"]
["link", "instance/event"] | ["flow", "@instance/event"]
["instance/link", "event"] | ["flow", "@instance/event"]
---------------------------*----------------------------
```

**Comment by IonicaBizau** [comment]
> `["link", "instance/event"] | ["flow", "instance/event"]`

Shouldn't it be `"@instance/event"`?

Also is it possible to have `["flow", "(@)(instance/)event"]` everywhere (not `instance/flow`)?

**Comment by ottiker** [comment]
Yes, the issue description is outdated, since we found out that `instance/emit` is "ugly" to visualize. I'll update the description.

**Comment by ottiker** [comment]
~~`instance/flow` is still possible, but will not be documented and used from the builder.~~

**Comment by IonicaBizau** [comment]
:+1: :cool:

**Comment by IonicaBizau** [comment]
> instance/flow is still possible, but will not be documented and used from the builder.

[Still there](https://github.com/jillix/engine#all-options)... :crying_cat_face:

**Comment by ottiker** [comment]
Yes, that's must be like this, that's because of the automatic loading of instances. Otherwise it's not logical. See the stream-network drawing for the visualization details.
