### ISSUE TITLE
Blank page after browser reload

### ISSUE THREAD

**Issue by ottiker** [jillix/flow-nodejs#268]
Sometimes the `C` core server event doesn't send a response message on the websocket. This happens because of a bug somewhere in the callback buffering in the composition module.

**Comment by IonicaBizau** [comment]
:+1: It also happened to me.

**Comment by ottiker** [comment]
@jillix/jxservice-devs Does anybody still sees this issue?

**Comment by IonicaBizau** [comment]
Yep!

**Comment by IonicaBizau** [comment]
I didn't see this anymore. Closing this for now. Hopefully it's really fixed. :smile:

**Comment by ottiker** [comment]
:satisfied:

**Comment by IonicaBizau** [comment]
```
WebSocket connection to 'ws://private.service.jillix.ch:10001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Uncaught TypeError: stream.write is not a function
```

**Comment by ottiker** [comment]
Let's continue this issue in #283
