### ISSUE TITLE
Append previous url parameters to route

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#27]
How to get a list with visited routes?

Maybe pushing all routes in an array `Z.history`?

**Comment by ottiker** [comment]
To go to the previous page just use the `history` api: `window.history.back();`

**Comment by IonicaBizau** [comment]
Not to go but to **get** its value.

**Comment by ottiker** [comment]
This issue can probably be closes when 2ac1555bbab52b103f883d607b0e8dbb44a5ea91 is merged. Cause now the url parameters are also in the previous route.

**Comment by IonicaBizau** [comment]
@adioo And how can I get previous route value?

**Comment by ottiker** [comment]
`window.history.back();` and then `window.location`

**Comment by ottiker** [comment]
Do we have a use case for getting the url string from the previous page, without changing the url in the browser?

**Comment by IonicaBizau** [comment]
Consider an eShop:
- `/?some=filter#foo` -> `/itm/view` -> Click back to products -> `/?some=filter#foo`
- `/itm/view` -> Click back to products -> `/`

`window.history.back()` only works in the first case, but not in the second one:
- `http://google.com`
- `hb.ch/itm/view` -> back (`history.back()`) -> `http://google.com` (instead of `hb.ch/`)

**Comment by ottiker** [comment]
A module has now the infos of the previous url in the route's state event object. This should allow the module to append the URL parameters to the route if needed.

@IonicaBizau Try to implement this solution in the HB shop detail view use case.

**Comment by IonicaBizau** [comment]
How to access state object, having the instance object?

**Comment by ottiker** [comment]
The state object is the first parameter in a route handler. It's like the event object.

**Comment by ottiker** [comment]
Change the previous state only when URL changes.

**Comment by ottiker** [comment]
Fixed in #47.
