### ISSUE TITLE
Find ways ensure uniqueness of streams

### ISSUE THREAD

**Issue by ottiker** [jillix/flow-nodejs#270]
Every time a `this.flow("event")` is called a new stream is created. This leads to redundant streams, if the module not carefully caches them.

**Comment by IonicaBizau** [comment]
Maybe one stream with the name `x` on instance `y`?

**Comment by ottiker** [comment]
Caching streams with `instance._name + eventName` will surely be part of the solution. See [here](https://github.com/jillix/engine/blob/unique-stream/lib/client/flow.js#L109). But there are additional cases, where simply caching the streams might not be enough, for example when you append data handlers in the module code.
