### ISSUE TITLE
Standardize the start function

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#275]
We have the `init` function which is called _once_ which is awesome.

But, when using `load`, the module doesn't know if it's already loaded or not: if it's not loaded, the init function will be called, but if it's already loaded, the module can't find that out.

So, I propose to have a `start` method which is called _always_: after the module is initialized or an instance loaded it (`["load", "foo"]`).

That would make the life easier.

**Comment by ottiker** [comment]
Better call the `start` method directly.
Example:

``` json
{
    "flow": [
        [
            "renderedDOM",
            "mySuperInstance/start"
        ]
    ]
}
```

This is better then, first load the instance and then let engine call a `start` method by default. There will be cases where such a behavior will cause conflicts. `load` is kinda legacy feature, we should not use `load` until there's no interaction with an instance.

**Comment by IonicaBizau** [comment]
Ok, but then we should consider to remove `load` completely... because it doesn't make sense without a `start` function...

**Comment by ottiker** [comment]
Yes, `load` should be obsolete, since instances are loaded, when a method is called. When we don't find a compelling use case until September, then we'll remove the `load` feature. :+1:
