### ISSUE TITLE
Using ALTR to get DOM info

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#280]
Currently it's a little bit hacky to get the attribute values of a DOM element reference:

``` js
/foo/{myDomElement.attributes.0.value}
```

Since the `attributes` are an array-like object, we cannot be sure we get the correct attribute.

What other related limitations we have here?

**Comment by ottiker** [comment]
A module should provide `DOM` related functionality, cause engines `ALTR` just handles data objects.
