### ISSUE TITLE
Flow method arguments merging

### ISSUE THREAD

**Issue by ottiker** [jillix/flow-nodejs#285]
There are three types of options/config/args in engine:
1. Instance config
2. Flow method args `["method", "arg"]`
3. The data chunk

Often there is options data in the data chunk itself. It would be nice to have a config like the `:ALTR` to get the options out of a data chunk, so the method handler does not have to do this step manually.

Proposal:

``` json
[
    "myMethod", {"optionX": "{from.data.chunk}"}
]
```

Further there could be a way to define default configs for every method, maybe in form if JSdocs, in the instance config or hard coded in the code. For the the module has to take care of ensuring the default values.

**Comment by IonicaBizau** [comment]
Just saw this: https://jqplay.org/

Could be an interesting toy for us! :smile: Maybe I will port it to an Engine module.

**Comment by ottiker** [comment]
Here is the library, which _jqplay_ is based on: https://stedolan.github.io/jq/
