### ISSUE TITLE
Document the flow example

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#295]
@adioo Can you please add inline comments for each element in [this list](https://github.com/jillix/engine/tree/flow-review#flow-config-all-combinations)?

That would make the understanding simpler.

**Comment by ottiker** [comment]
Updated the [docs](https://github.com/jillix/engine/tree/flow-review#flow-config-all-combinations).
Is clearer now? @IonicaBizau close the issue if so, or let me know what's still unclear.

**Comment by IonicaBizau** [comment]
@adioo Great! Thanks! :cake:
