### ISSUE TITLE
Run multiple applications same time

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#3]
Right now the `admin` app configuration is hardcoded in `engine`.

Please close this issue providing the steps to run two applications same time.

**Comment by ottiker** [comment]
This is already possible, we need to improve the interface of the admin application to see the running processes.

**Comment by ottiker** [comment]
This is already working and the UI and process start/stop related enhancements should be issues in the admin repo. Further the hole process infrastructure will be replaced anyway.
