### ISSUE TITLE
How can a module listen for an event that is emitted by multiple instances?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#30]
`self.on("^foo", ...);` will listen for events that start with `foo` emitted by `self`. Having 3 instances (`A`, `B` and `C`), how can `A` listen for all events that start with `foo` emitted by `B` and `C`?

A use case would be layout module that will listen for `getLocale` event (that can be emitted by each instance).

**Comment by ottiker** [comment]
@IonicaBizau is the issue obsolete now we have a `ready` event?

**Comment by IonicaBizau** [comment]
Well, you said in a hangout that _Engine is the reverse of Mono_, so we don't listen for same event emitted by multiple modules, but we can use `to` option to emit an event to specific modules.

So, this will not be fixed.
