### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#31]
- `_i18n` will contain the locale value

There are some changes regarding i18n in the layout module: https://github.com/jillix/layout/tree/locale

**Comment by ottiker** [comment]
@IonicaBizau see [this](https://github.com/jillix/engine/pull/32) pull request and look if gives you the tool you need to solve the i18n use case.

**Comment by IonicaBizau** [comment]
@adioo Yeps, [I already commented there](https://github.com/jillix/engine/pull/32#issuecomment-54047776).

**Comment by IonicaBizau** [comment]
Fixed via #32.
