### ISSUE TITLE
Handle absolute paths relatively to app dir (client)

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#310]
When doing in a module:

``` js
require("/path/to/file.js");
```

I expect that the absolute path (on the disk) looks like `/home/username/.../app/public/path/to/file.js`.

Currently getting: `Error: Cannot find module '/path/to/file.js' from ...`

**Comment by ottiker** [comment]
@IonicaBizau Is this supported by _browserify_?

**Comment by IonicaBizau** [comment]
I know browserify has a feature to `add` modules, so, yes, it's supported.

https://github.com/substack/node-browserify/#baddfile-opts

**Comment by ottiker** [comment]
Move issue to https://github.com/jillix/flow-pack/issues/4.
