### ISSUE TITLE
Don't keep the bundles in module directories

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#318]
...because it's not really `git` friendly. We would have to `gitignore` all these. But better just don't output them there.

**Comment by ottiker** [comment]
@IonicaBizau Any suggestion for a better solution?

**Comment by IonicaBizau** [comment]
@adioo Maybe engine should create an `.engine` directory to store such things?

**Comment by ottiker** [comment]
Moved issue to [flow-pack#3](https://github.com/jillix/flow-pack/issues/3).
