### ISSUE TITLE
Get the path sections

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#320]
For example, having the `/foo/bar/baz` url,how to get the second split in the url (`bar`) in the flow config?

**Comment by ottiker** [comment]
The flow config don't know anything about url's. Module data handlers must handle the _application_ logic. Such functionality should be implemented in the [flow-tools](https://github.com/jillix/flow-tools) module, or the `ruut` module could provide data handlers, which extend the data chunk with a url. After that the `translate` method of `flow-tools` can do reqex stuff.

**Comment by IonicaBizau** [comment]
Yeah, make sense, but we need a solution for that.

**Comment by ottiker** [comment]
Moved issue to https://github.com/jillix/flow-tools/issues/1
