### ISSUE TITLE
Send data to the server

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#321]
How to send data from the client to server?

**Comment by ottiker** [comment]
From Code:

``` js
var myEvent = this.flow("myEvent", {"net": "ws", "to": "instName"});
myEvent.on('error', function (err) {});
myEvent.on('data', function (chunk) {});
myEvent.write(data);
```

From composition:

``` json
{
    "flow": {
        "listenerName": {
            "d": [
                [">>myEvent", {"net": "ws"}]
            ]
        }
    }
}
```

The `net` option has two possible values `ws` and `http`. See the [flow docs](https://github.com/jillix/flow#flow-listener-config-flow), for a fulll overview of possible configurations.

**Comment by ottiker** [comment]
@IonicaBizau See the view module, to see how to emit flow events from the [code](https://github.com/adioo/view/blob/master/lib/events.js#L38-L59).

**Comment by IonicaBizau** [comment]
@adioo Isn't there a pure composition solution? Maybe a module we can use?

**Comment by ottiker** [comment]
@IonicaBizau Somewhere a module needs to emit flow events, in order to link, for ex. `DOM` events to the flow, or `URL`s events. After that, the flow composition handles the rest.
