### ISSUE TITLE
Server code from modules is exposed on the client

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#322]
The server code from modules is exposed on the client via the `bundle.js` files. This is terrible because it could contain sensitive information.

**Comment by gabipetrovay** [comment]
Whoops! :)

**Comment by IonicaBizau** [comment]
@gabipetrovay Maybe we should have an internal tracking of security issues to not publicly disclose them. :joy:

**Comment by ottiker** [comment]
In my opinion, module code isn't the best best place to store sensitive information. The `flow-pack` bundler, bundles now all modules no matter if they run only on the server, which can be fixed super easily. Further, an access check based on the `mic` role is also not to hard to implement.
And internal tracking of security issues would make sense for the _close-source_ API's but not for the _open-source_ flow-app repo.

**Comment by IonicaBizau** [comment]
> In my opinion, module code isn't the best best place to store sensitive information.

But in general you don't want the server code to be exposed on the client, unless the entire module is open-source and the server side is visible on GitHub or so.

If this is expected, why do we not open-source everything, all the modules (server + client) being visible to everyone, anyways?

> And internal tracking of security issues would make sense for the close-source API's but not for the open-source flow-app repo.

Just image lots of websites being powered by this thingy and someone finds out a critical security issue. By disclosing it publicly, everyone can hack all these websites. :cry:

**Comment by gabipetrovay** [comment]
You can imagine that people will build modules that are not open-source. They for sure will not want them to be visible. Also, the developer is free to program whatever he wants in the module including, API keys, secrets, passwords, etc. So it might make sense no to have server code visible. Even if it is not the best practice, people will do it. I also believe that it is not a good practice to store secrets. But allowing everyone so see the server code will open more security issues even if the code does not contain sensitive information (reverse engineering, server architecture, etc.)

**Comment by ottiker** [comment]
Recap:

> The flow-pack bundler, bundles now all modules no matter if they run only on the server, which can be fixed super easily.

The issue is understood and will be fixed, Just no prio yet.

> Further, an access check based on the mic role is also not to hard to implement.

Even a composition role check, to know if a role has access to a particular module. So only roles which have _somewhere_ access to a module instance composition (`mic`), of the requested module
