### ISSUE TITLE
How to send custom events

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#323]
E.g. _fetched data_ or something similar, from the code

**Comment by ottiker** [comment]
https://github.com/jillix/flow#emit-a-stream-event

**Comment by IonicaBizau** [comment]
@adioo Hmm... but you previously said that's not a good practice? I'm not really sure what's the good practice here.

**Comment by ottiker** [comment]
@IonicaBizau See view module for a [good](https://github.com/adioo/view/blob/master/lib/events.js#L41-L52) example. Please provide more context, so I can fully understand your perspective.

**Comment by IonicaBizau** [comment]
:+1: Looks good!
