### ISSUE TITLE
The init function is called in a weird way

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#324]
I have two modules: **`foo_layout`** and **`foo_graph`**. `foo_graph` depends on the `foo_layout` DOM. So, it has to wait until `foo_layout` is ready.

In `foo_layout` I have something like this:

``` json
{
    "flow": {
        "ready": {
            "d": [
                [">>getGraphData", {
                    "to": "some_api",
                    "net": "ws"
                }],
                ":foo_graph/render"
            ]
        }
    }
}
```

The DOM from `foo_layout` is ready the `render` function is called, but not when the `init` function of the `foo_graph` is called. Isn't the `init` method supposed to be called when the module is loaded, so basically, when we first call `foo_graph/render`?

**Comment by ottiker** [comment]
A module is loaded and `init` function is called, when the event (in this case _ready_) is built. And also you need to call the `ready` handler in the init method, See [here](https://github.com/jillix/flow#ready-listener). Otherwise the _ready_ event will never be emitted.

**Comment by IonicaBizau** [comment]
Ah, got it. Thanks!
