### ISSUE TITLE
Show a relevant error when there is a syntax error

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#325]
Currently from `events.js` we get this log:

![image](https://cloud.githubusercontent.com/assets/2864371/12714542/1202d01e-c8de-11e5-9ff0-0be7d84579cd.png)

But that doesn't help. In fact, one of the `flow-flow-api` dependencies was broken, but I had to manually find where the error is.

**Comment by ottiker** [comment]
Moved issue to https://github.com/jillix/flow/issues/12.
