### ISSUE TITLE
Improve url parser

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#37]
- parse search and hashes
- `item`: `/foo/{bar}` vs `item`: `/foo/{bar}/`

**Comment by ottiker** [comment]
Should the URL query `?key=value` be appended to the data object automatically?

**Comment by IonicaBizau** [comment]
I think that only when we need these values... Or maybe storing them in a field like `_search`.

**Comment by ottiker** [comment]
The data object will be extended with following keys:
- if query parameters are in the url `data._search: {key: value}`
- if hash exists in url `data._hash: "string"`
