### ISSUE TITLE
What is this?!

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#38]
![screenshot from 2014-09-02 19 17 42](https://cloud.githubusercontent.com/assets/2864371/4121602/b99eb31a-32bc-11e4-8c1e-a64075504c2b.png)

**Comment by ottiker** [comment]
looks like a MongoDB `ObjectId()`

**Comment by IonicaBizau** [comment]
Weird.

``` sh
$ rm -rf node_modules
$ npm install
```
