### ISSUE TITLE
Handle server crashes and errors

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#39]
The following snippet will catch all server crashes and log the error.

``` js
process.on("uncaughtException", function (err) {
   Debug.log(err, "error");
});
```

However, we need to send a good message to client that something went wrong.

How can we do that?

`try - catch`?

**Comment by ottiker** [comment]
Some Infos regarding this issue: http://nodejs.org/api/domain.html

**Comment by IonicaBizau** [comment]
Also here: http://stackoverflow.com/q/25957449/1420197

**Comment by IonicaBizau** [comment]
Can I hack this, @adioo?

I implemented this in `statique` library: https://github.com/IonicaBizau/node-statique/pull/16/files

**Comment by ottiker** [comment]
We have to consider this advice [here](http://nodejs.org/api/domain.html#domain_warning_don_t_ignore_errors).

**Comment by IonicaBizau** [comment]
@adioo Yes, I see. But for that we must consider clusters.

**Comment by ottiker** [comment]
When a process throws an Error that would make a process to terminate, we need to terminate the process anyway. Otherwise there would be leaking connections. This issue is about a nice way to terminate a process and closing all connections etc.

**Comment by ottiker** [comment]
http://nodejs.org/docs/latest/api/process.html#process_event_uncaughtexception

> Note that uncaughtException is a very crude mechanism for exception handling and may be removed in the future. Don't use it, use domains instead. If you do use it, restart your application after every unhandled exception!

**Comment by IonicaBizau** [comment]
I'm [not sure this event will be removed](https://github.com/joyent/node/commit/a2fd657b10c7609e1776004156a8cd3016e2c6c8). 

See the entire discution here: https://github.com/joyent/node/issues/2582

**Comment by ottiker** [comment]
Process terminations and error log handling will be part of the service API, that starts, stops and logs processes. Engine itself should be just a simple process, that can be managed by existing tools, like http://kubernetes.io
