### ISSUE TITLE
CSS minifier removes `@import url` calls

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#40]

**Comment by ottiker** [comment]
I can not reproduce the issue. @IonicaBizau Can you post a css example?

**Comment by ottiker** [comment]
In my tests the `@import` rule were never removed, though I set the `processImport` option in the css-minifier to `false`. This disables the `@import` processing and leaves the `@import` rule untouched. See this commit d8fc1e0a7880aa2e563087758d8fbfe621fe2519

**Comment by ottiker** [comment]
Fixed in d8fc1e0a7880aa2e563087758d8fbfe621fe2519
