### ISSUE TITLE
Add search param

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#42]
How to add a search param?

`location.search = "?foo=bar"` refreshes the page. 

`url.js` library has `updateParam` method: https://github.com/jillix/url.js/blob/f709165fdabac8c20185dfb41f1147a1513d6e17/README.md#updatesearchparamparam-value

Do we have something like this in engine?

**Comment by ottiker** [comment]
The `route` doesn't reload the page and can have search params. But a `updateSearchParam` functionality should be handled in a module, not in the `Z.js`.

**Comment by ottiker** [comment]
The functionality to change a URL parameter value, without reloading the page should be handled inside of an module.

**Comment by IonicaBizau** [comment]
I am working on this and will post here the solution.

**Comment by IonicaBizau** [comment]
Using [`engine-url-extra`](https://github.com/IonicaBizau/engine-url-extra) this is possible.

`self.updateSearchParam(param, value)`
