### ISSUE TITLE
Runtime observer

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#51]
Is it possible to render runtime observer configuration?

**Comment by ottiker** [comment]
You mean creating an observer config `O` on runtime and then pass it to the [observe](https://github.com/jillix/engine/blob/master/lib/client/Z.js#L705) function?

**Comment by IonicaBizau** [comment]
Yes! Something like the old internal binds: https://github.com/jillix/bind-table-crud/blob/67d06940ebf30b9c29b5c0add7b85c155819425d/table.js#L135-L168

**Comment by ottiker** [comment]
I don't think this is a good idea. Cause listeners should be handle with the composition and if module starts to use create observer configs, things get complicated. Also for the "AppBuilder".

**Comment by ottiker** [comment]
@IonicaBizau Please close this issue if you agree with the above comment.
