### ISSUE TITLE
How to get the HTML of a non-rendered view?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#53]
I want to get raw HTML of a view that is not rendered.

**Comment by ottiker** [comment]
You mean the HTML string, or the DOM?

**Comment by IonicaBizau** [comment]
The HTML as string. I cannot get the DOM reference because the view is not rendered.

**Comment by ottiker** [comment]
But there should be an also option to get a DOM fragment, even if it's not appended to the DOM itself. This, and the HTML string, can be easily implemented into the view.

**Comment by ottiker** [comment]
@IonicaBizau Do you have a use case for this feature?

**Comment by IonicaBizau** [comment]
https://github.com/IonicaBizau/engine-list/issues/3

Custom HTML rendering.

**Comment by ottiker** [comment]
The HTML can be accessed with the `on.html` handler, as described [here](https://github.com/jillix/engine/issues/50#issuecomment-54742112). In combination with the `leaveKeys` option in the render method, we have access to the raw HTML.

**Comment by IonicaBizau** [comment]
If we already have the view HTML, why not to be able to access it (for a non-rendered view)?
