### ISSUE TITLE
Handle load configuration in a act handler with the "loader" function

### ISSUE THREAD

**Issue by danandrei** [jillix/flow-nodejs#63]
![screenshot 2014-09-15 15 49 05](https://cloud.githubusercontent.com/assets/4629089/4285943/dfd63a5a-3d8c-11e4-821f-1e40fee840a4.png)
If you have a configuration similar to the one in this screenshot where the `range_slider` emits something on ready event to the `api_range_slider`, it will not always work (works mostly with devTools closed and cache enabled), this may be caused by the fact that the `range_slider` instance emits the event to `api_range_slider` before it is loaded.

**Comment by ottiker** [comment]
This problem can be solved, when the hierarchy of the elements are changed.
The current configuration is this:
`root > [listener] > load: range_slider + api_range_slider`
If the configuration would be like this, the problem would be solved:
`root > load: api_range_slider > [listener] > load: range_slider`

Though it should also work with the current configuration. It's not stable, cause the elements in a `A` load configuration are not loaded via the [loader](https://github.com/jillix/engine/blob/d80c0257e704205a684d605accc6f45512797265/lib/client/Z.js#L640-L642) method.

**Comment by ottiker** [comment]
@danandrei please reopen this issue if you still have the wrong behavior.
