### ISSUE TITLE
Emit event and call

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#66]
How to emit `event` and `data`, `call`ing a module method?

``` js
self.emit({
  event: {foo: "event"}, // This should be a string I guess
  data: {bar: "data"},
  call: "fooMethod"
});
```

And in module:

``` js
self.fooMethod = function (ev, data) {
  ev; // {foo: "event"}
  data; // {bar: "data"}
  ...
};
```

**Comment by ottiker** [comment]
Calling methods on the same instance should be done over the `self`. And calling methods of an other instance from the code is not possible. This can be done with an `event` that the target instance is listening to and calls a method on the emitted `event`.

Target  instance observe config:

``` json
{
    "re": "myEvent",
    "A": {
        "emit": [{
            "call": "myMethod"
        }]
    }
}
```

In the code of the emitting instance:

``` js
// call a method on a instance from the code
// is a bad idea, cause there is a hard coded instance name!
self.emit({
    event: "myEvent"
    to: "targetInstance"
    data: {}
});

// ...and call a method
self.myMethod();
```

**Comment by IonicaBizau** [comment]
Thanks!
