### ISSUE TITLE
require doesn't work on client anymore

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#71]
``` js
require("./ui")
```

Probably because of #69

**Comment by IonicaBizau** [comment]
https://github.com/IonicaBizau/engine-list/blob/faa86155b74d1df8d49c93c1098794fcbd8b3178/client/main.js#L1-L2

**Comment by IonicaBizau** [comment]
https://github.com/jillix/composition-visualization/blob/aecdb4590e746cf68b219e0380991985daca7b74/composition/modules/github_ionicabizau_list_v0.0.1.json

**Comment by ottiker** [comment]
Probably we need to remove the file's fingerprint inside the require logic.

**Comment by IonicaBizau** [comment]
Exactly.
