### ISSUE TITLE
Do not define clone and blend properties

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#72]
https://github.com/jillix/engine/blob/eb1341e8b094856d3f66fb43c68ab9eed47e60e0/lib/utils/extend.js

...otherwise, modules will crash when setting `clone` or `blend` functions.

**Comment by ottiker** [comment]
The `clone` function is needed for creating instances.

**Comment by ottiker** [comment]
Create a utils module, which exports this functionality, to solve this problem.
