### ISSUE TITLE
Automatic Z.wrap prepend

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#9]
Scenario:

I have `github_ionicabizau_list_v0.0.1.json` module in `composition` directory, containing the module configuration:

``` json
{                                                       
    "roles": {                                          
        "*": true                                       
    },                                                  
    "url": "git@github.com:IonicaBizau/engine-list.git",
    "name": "github_ionicabizau_list_v0.0.1",           
    "main": "server/main.js",                           
    "dependencies": [                                   
        "./client/main.js"                              
    ]                                                   
}                                                       
```

---

In the module client side (`./client/main.js`) we have the wrapping thing:

``` js
Z.wrap('github/ionicabizau/list/v0.0.1/main.js', function (require, module, exports) {...});
```

However, the script is not loaded. What value am I supposed to pass as first parameter in `Z.wrap` function?

---

Automatic Z.wrap prepend should be implemented, like in the old Mono. If possible, without changing the file content but in application cache only.

**Comment by IonicaBizau** [comment]
The path `github/ionicabizau/list/v0.0.1/main.js` was wrong because the `client` directory is missing.

The correct one is `github/ionicabizau/list/v0.0.1/client/main.js`.

**Comment by ottiker** [comment]
The name of the module can not contain a `/`, cause it's a file in the file system.
Just reopen this issue if we run into problems regarding module naming.

**Comment by IonicaBizau** [comment]
This is still a problem when the name of the module is different than the name of the repository (e.g. `github/ionicabizau/list/v0.0.1/main.js` vs `github/ionicabizau/engine-list/v0.0.1/main.js`. Since `Z.wrap` requires the module application name, this is an issue that forces devs to use `list` module name for this module.

The best solution would be automatic wrapping, like in the old Mono.

**Comment by ottiker** [comment]
The module name will be generated with the git url, since the module name is engine internal.
The wrapping path module name must always be equal with the git repo name. Like this the developer can choose what ever name he like for his module.

**Comment by ottiker** [comment]
But automatic wrapping makes sense.

**Comment by IonicaBizau** [comment]
Maybe we can wrap only minified/cached files, avoiding overriding files on disk.
