### ISSUE TITLE
Log data

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#90]
- error
- warning
- info 
- log

[Original issue](https://github.com/jillix/mono/issues/62)

**Comment by ottiker** [comment]
Every `release` (version) in a `project` and the `dev` process has a log and the log data will be visible in the `jillix/service` app.

**Comment by ottiker** [comment]
The engine just starts the processes, the service app is responsible to handle the output of a process. So this issue is already [here](https://github.com/jillix/service/issues/11) in the jillix/service repo.
