### ISSUE TITLE
Set/Unset data from session

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#92]
How to store/remove data in/from session?

**Comment by ottiker** [comment]
A `session` stores only those values:
- role
- user ID
- locale

Use a `model` to save and retrieve data, related to a user or a session.

**Comment by ottiker** [comment]
To save data on the session, just append the data to the the `session` object in `link.session`.
Example:

``` js
// set the data
link.session.myData = {what: "ever"};
link.session.save();

// access the data in the next request ->
link.session.myData;
```
